apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hqc265-db1
  name: hqc265-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hqc265-db1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: hqc265-db1
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: hqc265
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: myuser
        image: mysql:latest
        imagePullPolicy: ""
        name: hqc265-db1
        resources: {}
      hostname: hqc265-db1
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
