apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd:
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hqc265-web1
  name: hqc265-web1
spec:
  type: LoadBalancer
  ports:
    - name: '12075'
      port: 12075
      targetPort: 12075
  selector:
    io.kompose.service: hqc265-web1
status:
  loadBalancer: {}
