apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd:
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hqc265-db1
  name: hqc265-db1
spec:
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: hqc265-db1
status:
  loadBalancer: {}
