apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hqc265-web1
  name: hqc265-web1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hqc265-web1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: hqc265-web1
    spec:
      containers:
      - image: cjgarc0724/flask-web-service
        imagePullPolicy: ""
        name: hqc265-web1
        ports:
        - containerPort: 12075
        resources: {}
      hostname: web1
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
